name: Build React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from the Actions interface

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1' # Specify your Node.js 

      # Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Build the React app
      - name: Build
        run: npm run build
